config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :gists, only: %i[index create]
  resources :badges, only: %i[index achieve]

  namespace :admin do
    resources :badges, only: %i[index create new]

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true

  scope :correct, -> { where(correct: true) }

  validate :validate_answer_count

  def validate_answer_count
    errors.add(:question_id) unless question.answers.count < 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  validates :title,
            :pic_url,
            :description,
            :rule,
            presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question

  validates :body, presence: true
  validates :answers, presence: true, on: :use
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }

  scope :by_level, ->(level) { where(level: level) }
  scope :by_easy, -> { by_level(0..1) }
  scope :by_normal, -> { by_level(2..4) }
  scope :by_hard, -> { by_level(5..) }
  scope :by_category, ->(category) { where(category: category) }

  def self.titles(category)
    by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  scope :by_uncomplete, -> { where.not(current_question: nil).order(id: :desc) }
  scope :success, -> { select { |tp| tp.result_success } }

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def test_passage_result
    correct_questions * 100 / test.questions.count
  end

  def result_success
    test_passage_result > SUCCESS_RATIO
  end

  def current_question_index
    test.questions.pluck(:id).index(current_question_id)
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    unless current_question.nil?
      self.current_question = test.questions.order(:id).where('id > ?',
                                                              current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable

  has_many :tests, inverse_of: 'author', foreign_key: 'author_id', dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :tests_passed, through: :test_passages, source: :test
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def uncomplete_test_passage(test)
    test_passages.by_uncomplete.find_or_create_by(test_id: test.id)
  end

  def tests_passed_succesful
    test_passages.success.map(&:test)
  end

  def tests_passed_times(value)
    tests = tests_passed_succesful
    tests.select { |test| tests.to_a.count(test) >= value }.uniq
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < Admin::BaseController
  skip_before_action :admin_required!, only: :create

  def index
    @gists = Gist.all
  end

  def create
    @test_passage = TestPassage.find(params[:test_passage_id])

    result = GistQuestionService.new(@test_passage.current_question).call

    flash_options = result.success? ? save_record_gist(result) : { notice: t('.failure') }

    redirect_to @test_passage, flash_options
  end

  private

  def save_record_gist(result)
    @gist = Gist.new(user: current_user, url: result.url, question: @test_passage.current_question)

    if @gist.save
      { notice: "#{t('.success')} #{result.url}".html_safe }
    else
      { notice: t('.failure') }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_contents(type)
    content_tag :p, flash[type], class: "flash #{type}" if flash[type]
  end
end

app/helpers/footer_helper.rb
module FooterHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to author, repo, target: '_blank'
  end
end

app/helpers/gists_helper.rb
module GistsHelper
  def gist_hash(string)
    string.delete 'https://gist.github.com/'
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def test_search; end

  def nav_registration
    if user_signed_in?
      "Welcome, #{current_user.email}"
    else
      link_to "I'm not Guru, yet", new_user_registration_path
    end
  end

  def nav_menu
    if user_signed_in?
      if !current_user.is_a? Admin
        render 'shared/menu'
      else
        render 'admin/menu'
      end
    else
      link_to 'Login', new_user_session_path
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    (@question.new_record? ? 'Create New' : 'Edit') + " question for #{@question.test.title} test"
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 1 => :Elementary, 2 => :Easy, 3 => :Advanced, 4 => :Hard }.freeze

  def test_level(test)
    TEST_LEVELS.fetch(test.level, 'Very hard')
  end
end

app/views/admin/_menu.html.erb
<ul class="menu hide">
  <li class="menu-list nav-admin"><%= link_to t('.logout'), destroy_user_session_path, method: :delete %></li>
  <li class="menu-list nav-admin"><%= link_to t('.new_test'), new_admin_test_path %></li>
  <li class="menu-list nav-admin"><%= link_to t('.new_badge'), new_admin_badge_path %></li>
  <li class="menu-list nav-admin"><%= link_to t('.badges'), admin_badges_path %></li>
  <li class="menu-list nav-admin"><%= link_to t('.gists'), gists_path %></li>
</ul>

app/views/admin/_navigation.html.erb
<div class="nav nav-admin">
  <span class="title"><%= link_to 'TestGuru', admin_tests_path %></span>

  <div class="user">
    <%= nav_registration %>
    <%= nav_menu %>
  </div>
</div>

app/views/admin/badges_rules/_form.html.erb
<%= form_with model: [:admin, @badges_rule], local: true do |form| %>
  <div>
    <p>
      <%= form.label t('.title') %>
      <%= form.text_field :title %>
    </p><br>

    <p>
      <%= form.label t('.level') %>
      <%= form.number_field :level %>
    </p><br>

    <p>
      <%= form.label t('.category') %>
      <%= form.collection_select :category_id, Category.all, :id, :title, prompt: true %>
    </p><br>

    <p>
      <%= form.label t('.test') %>
      <%= form.collection_select :test_id, Test.all, :id, :title, prompt: true %>
    </p><br>

    <p>
      <%= form.label t('.attempts') %>
      <%= form.number_field :attempts %>
    </p><br>

    <p>
      <%= form.label t('.pic_url')%>
      <%= form.text_field :pic_url %>
    </p>
  </div>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges_rules/new.html.erb
<h1><%= t('.header') %></h1>

<h2><%= t('.description') %></h2>

<%= render 'shared/errors', resource: @badges_rule %>
<%= render 'form' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/navigation' %>

    <%= render 'shared/flash' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>

    <%= render 'shared/flash' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_column_names.html.erb
<th class="sort-by-title %> pointer">
  <%= locals[:col_name] %>
  <%= octicon 'arrow-up', class: 'text-success hide' %>
  <%= octicon 'arrow-down', class: 'text-success hide' %>
</th>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |f| %>
  <%= flash_contents(f[0]) %>
<% end %>

app/views/shared/_footer.html.erb
<div>
  <h3>Now you can create, edit and delete tests with questions, web interface is cool!</h3>
  <table>
    <tr>
      <td><%= github_url('Test Guru', 'https://github.com/MaxSandulsky/TestGuru') %></td>
      <td><%= github_url('Maxim Sandulsky', 'https://github.com/MaxSandulsky') %></td>
    </tr>
    <tr>
      <td><%= current_year %></td>
      <td><%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com/' %></td>
    </tr>
  </table>
</div>

app/views/shared/_menu.html.erb
<ul class="menu hide">
  <li class="menu-list nav-user"><%= link_to t('.logout'), destroy_user_session_path, method: :delete %></li>
  <li class="menu-list nav-user"><%= link_to t('.badges'), badges_path %></li>
</ul>

app/views/shared/_navigation.html.erb
<div class="nav nav-user">
  <span class="title"><%= link_to 'TestGuru', tests_path %></span>

  <div class="user">
    <%= nav_registration %>
    <%= nav_menu %>
  </div>
</div>