config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :gists, only: %i[index create]
  resources :badges, only: %i[index achieve]

  namespace :admin do
    resources :badges, only: %i[index create new]

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question

  validates :body, presence: true
  validates :answers, presence: true, on: :use
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  scope :by_uncomplete, -> { where.not(current_question: nil).order(id: :desc) }
  scope :success, -> { select { |tp| tp.result_success } }

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def test_passage_result
    correct_questions * 100 / test.questions.count
  end

  def result_success
    test_passage_result > SUCCESS_RATIO
  end

  def current_question_index
    test.questions.pluck(:id).index(current_question_id)
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_update_set_next_question
    unless current_question.nil?
      self.current_question = test.questions.order(:id).where('id > ?',
                                                              current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      BadgeManagerService.new(@test_passage).call
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  MS_IN_SEC = 1000
  MS_IN_MIN = 60_000

  def result_text
    @test_passage.result_success ? 'Success' : 'Failure'
  end

  def result_color
    @test_passage.result_success ? 'green' : 'red'
  end

  def timer
    text = content_tag :div, content_tag(:span, t('.time_left'))

    time = content_tag :span, '0:00:00', class: 'timer',
                                         data: { time_limit: min_to_ms(@test_passage.test.timer),
                                                 time_now: sec_to_ms(Time.now.to_i),
                                                 time_start: sec_to_ms(@test_passage.created_at.to_i) }
    text.concat(time) unless @test_passage.test.timer == 0
  end

  def sec_to_ms(secs)
    secs * MS_IN_SEC
  end

  def min_to_ms(mins)
    mins * MS_IN_MIN
  end
end

app/views/test_passages/result.html.erb
<h1>Test <%= @test_passage.test.title %> was completed!</h1>

<p>
  <h1>Result:</h1>
  <h2 style="color:<%= result_color %>;"><%= result_text %> with <%= @test_passage.test_passage_result %>% correct answers</h2>
</p>

app/views/test_passages/show.html.erb
<h1><%= "#{t('.header')} #{@test_passage.test.title}" %></h1>

<p>
  <% 50.times do |i|%>
    <%= content_tag :span, '', class: "progress-bar tile-#{i}" %>
  <% end %>
</p>

<p>
  <%= timer %>
</p>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>

<%= form_with url: test_passage_path(@test_passage),
              class: 'test-passage',
              local: true,
              method: :put do |form| %>

  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers,
  :id, :body, include_hidden: false do |box| %>
    <p>
      <%= box.check_box id: "answer_ids_#{box.object.id}" %>
      <%= box.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist Question', gists_path(test_passage_id: @test_passage.id), method: :post %></p>

  <p>
    <%= form.submit 'Next',
                      data: { question_index: @test_passage.current_question_index,
                              questions_count: @test_passage.test.questions.count } %>
  </p>
<% end %>