config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :gists, only: %i[index create]
  resources :badges, only: %i[index achieve]

  namespace :admin do
    resources :badges, only: %i[index create new]

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true

  scope :correct, -> { where(correct: true) }

  validate :validate_answer_count

  def validate_answer_count
    errors.add(:question_id) unless question.answers.count < 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy

    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.body %><br>
  <%= link_to t('.show'), admin_answer_path(answer) %>
  <%= link_to t('.edit'), edit_admin_answer_path(answer) %>
  <%= link_to t('.delete'), admin_answer_path(answer),
                      method: :delete,
                      data: { confirm: t('.confirm') } %>
</li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body, t('.body') %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct, t('.correct') %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p><%= form.submit t('.create') %></p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.title') %></h1>

<p>
  <h3><%= t('.body') %> <%= @answer.question.body %></h3>
</p>

<%= render 'form'%>

<%= link_to t('.back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1><%= t('.title') %> <%= @question.body %></h1>

<%= render 'form'%>

<%= link_to t('.back'), admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.title') %> <%= @answer.question.body %></h1>

<p>
  <b><%= t('.body') %></b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t('.correct') %></b>
  <%= @answer.correct %>
</p>

<%= link_to t('.edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('.back'), admin_question_path(@answer.question) %>