config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :gists, only: %i[index create]
  resources :badges, only: %i[index achieve]

  namespace :admin do
    resources :badges, only: %i[index create new]

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: :current_question

  validates :body, presence: true
  validates :answers, presence: true, on: :use
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_record_not_found

  def show; end

  def new
    set_question
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to edit_admin_test_path(@test)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to edit_admin_test_path(@question.test)
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = @test.questions.new
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_record_not_found
    render plain: 'Record not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header
    (@question.new_record? ? 'Create New' : 'Edit') + " question for #{@question.test.title} test"
  end
end

app/views/admin/questions/_form.html.erb
<%= question_header %>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <div>
    <p>
      <%= form.label :body %>
      <%= form.text_field :body %>
    </p><br>
  </div>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= link_to question.body, admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
  <td><%= link_to 'Delete', admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/questions/edit.html.erb
<h1>Edit question</h1>

<%= link_to 'Back', admin_test_path(@question.test)%><br>

<%= render 'form' %>

app/views/admin/questions/new.html.erb
<h1>Create new question for test <%= @test.title %></h1>

<%= render 'form' %>
<%= link_to 'Back', admin_test_path(@test) %>

app/views/admin/questions/show.html.erb
<h1><%= t('.test') %> <%= @question.test.title %></h1>

<p>
  <h2><%= t('.title') %> <%= @question.body %></h2>
</p>

<h2><%= t('.answers') %></h2>

<%= link_to t('.new'), new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to t('.edit'), edit_admin_question_path(@question) %>
<%= link_to t('.back'), admin_test_path(@question.test) %>